# Generated by Django 2.1.7 on 2019-06-12 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obp', '0003_auto_20190613_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_of_delivery',
            name='variableX1',
            field=models.PositiveSmallIntegerField(default='1', verbose_name='Цена если сумма заказа > Y'),
        ),
        migrations.AddField(
            model_name='type_of_delivery',
            name='variableX2',
            field=models.PositiveSmallIntegerField(default='1', verbose_name='Цена если сумма заказа < Y'),
        ),
        migrations.AlterField(
            model_name='client_auth',
            name='end_of_live',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 2, 4, 11, 44838)),
        ),
        migrations.AlterField(
            model_name='type_of_delivery',
            name='variableY',
            field=models.PositiveSmallIntegerField(default='1', verbose_name='Значение переменной Y'),
        ),
    ]
