# Generated by Django 2.1.7 on 2019-06-13 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obp', '0005_auto_20190613_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obp.Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obp.Product')),
            ],
        ),
        migrations.AlterField(
            model_name='client_auth',
            name='end_of_live',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 16, 26, 41, 307937)),
        ),
    ]
