# Generated by Django 2.1.7 on 2019-06-13 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obp', '0006_auto_20190613_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_auth',
            name='end_of_live',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 17, 55, 15, 417369)),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ожидание подтверждения', 'Ожидание подтверждения'), ('В обработке', 'В обработке'), ('Ожидается самовывоз', 'Ожидается самовывоз'), ('Ожидается отправки', 'Ожидается отправки'), ('В пути', 'В пути'), ('Заказ получен', 'Заказ получен'), ('Заказ отклонен', 'Заказ отклонен')], default='Ожидание подтверждения', max_length=30, verbose_name='статус'),
        ),
    ]
