# Generated by Django 2.1.7 on 2019-06-13 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obp', '0007_auto_20190613_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_auth',
            name='end_of_live',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 17, 58, 5, 275385)),
        ),
    ]
