# Generated by Django 2.1.7 on 2019-06-17 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obp', '0010_auto_20190617_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_auth',
            name='end_of_live',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 21, 16, 58, 489253)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryCost',
            field=models.IntegerField(default='0', verbose_name='сумма доставки'),
        ),
    ]
