# Generated by Django 2.1.7 on 2019-06-17 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obp', '0011_auto_20190617_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_auth',
            name='end_of_live',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 21, 45, 17, 714065)),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryCost',
            field=models.DecimalField(decimal_places=1, default='0', max_digits=4, verbose_name='сумма доставки'),
        ),
    ]
