# Generated by Django 2.1.7 on 2019-06-18 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obp', '0013_auto_20190618_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_auth',
            name='end_of_live',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 18, 17, 38, 49, 416123)),
        ),
    ]
