# Generated by Django 2.1.7 on 2019-06-19 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obp', '0015_auto_20190618_1730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='type_of_delivery',
        ),
        migrations.AlterModelOptions(
            name='client_auth',
            options={'verbose_name': 'Код для авторизации клиента', 'verbose_name_plural': 'Коды для авторизации клиентов'},
        ),
        migrations.AlterModelOptions(
            name='product_comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='product_rating',
            options={'verbose_name': 'Рейтинг товара', 'verbose_name_plural': 'Рейтинг товаров'},
        ),
        migrations.AlterModelOptions(
            name='special_offers',
            options={'verbose_name': 'Специальная категория', 'verbose_name_plural': 'Специальные категории'},
        ),
        migrations.AlterField(
            model_name='client_auth',
            name='end_of_live',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 23, 30, 32, 395510)),
        ),
    ]
