# Generated by Django 2.1.7 on 2019-06-19 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obp', '0017_auto_20190619_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_auth',
            name='end_of_live',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 19, 23, 44, 34, 310461)),
        ),
        migrations.AlterField(
            model_name='special_offers',
            name='title',
            field=models.CharField(default=2, max_length=30, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
